config/routes.rb
Rails.application.routes.draw do
  resources :homes, :only => [:index] do
    collection do 
      get :search_index
    end
  end
  resources :contact_groups do
    resources :share_invites, shallow: true, :only => [:new, :create, :destroy] do
      member do
        get :accept
        get :decline
      end
    end
  end
  resources :contacts
  devise_for :users
  resources :share_invites, :only => [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
end

app/models/contact_group.rb
class ContactGroup < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :contacts, dependent: :destroy
  has_many :share_invites, dependent: :destroy
    validates :group_name, presence: true
end

app/controllers/contact_groups_controller.rb
class ContactGroupsController < ApplicationController
  before_action :set_contact_groups, only: [:index]
  before_action :set_contact_group, only: [:show, :edit, :update, :destroy, :share_create, :share_new]

  # GET /contact_groups
  # GET /contact_groups.json
  def index
    @contact_groups = ContactGroup.where(user_id: current_user.id)
  end

  # GET /contact_groups/1
  # GET /contact_groups/1.json
  def show
      respond_to do |format|
        format.html { session[:contact_group_id] = @contact_group.id; redirect_to homes_url; }
        format.js 
      end
  end

  # GET /contact_groups/new
  def new
    @contact_group = ContactGroup.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contact_groups/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /contact_groups
  # POST /contact_groups.json
  def create
    @contact_group = ContactGroup.new(contact_group_params)
    @contact_group.owner_id = current_user.id
    respond_to do |format|
      if @contact_group.save
        @contact_group.users << current_user
        session[:contact_group_id] = @contact_group.id
        format.html { redirect_to @contact_group, notice: 'Contact group was successfully created.' }
        format.js { redirect_to homes_url, notice: 'Group successfully created.' }
        format.json { render :show, status: :created, location: @contact_group }
      else
        format.html { render :new }
        format.js
        format.json { render json: @contact_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_groups/1
  # PATCH/PUT /contact_groups/1.json
  def update
    respond_to do |format|
      if @contact_group.update(contact_group_params)
        format.html { redirect_to @contact_group, notice: 'Contact group was successfully updated.' }
        format.js { redirect_to homes_url, notice: 'Group successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_group }
      else
        format.html { render :edit }
        format.js
        format.json { render json: @contact_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_groups/1
  # DELETE /contact_groups/1.json
  def destroy
    if @contact_group.owner_id == current_user.id
      @contact_group.destroy
      respond_to do |format|
        format.html { redirect_to homes_url, notice: 'Contact group was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to homes_url, alert: "You must be the owner of the group to delete it" }
        format.js { redirect_to homes_url, alert: "You must be the owner of the group to delete it" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_group
      @contact_group = current_user.contact_groups.find(params[:id])
    end

    def set_contact_groups
      @contact_groups = current_user.contact_groups
    end 

    def create_group_if_none
      if @contact_groups.present?
        logger.debug "contact_group exists"
      else
        x = ContactGroup.create(group_name: "Default", default: "true" )
        x.users << current_user
        logger.debug "Default contact_group created"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_group_params
      params.require(:contact_group).permit(:group_name, :share_id, :id)
    end
end

app/helpers/contact_groups_helper.rb
module ContactGroupsHelper
end

app/views/contact_groups/_edit_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= bootstrap_form_with(model: @contact_group, remote: true) do |form| %>
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Edit Group</h4>
        <button type="button" class="close" data-dismiss="modal">x</button>
      </div>
      <div class="modal-body">

        <div class="field">
          <%= form.label :group_name %>
          <%= form.text_field :group_name, hide_label: true %>
        </div>

      </div>
      <div class="modal-footer">
        <div class="actions" >
          <%= form.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contact_groups/_groups_nav.html.erb
<ul class="nav nav-treeview">  
  <% @contact_groups.each do |contact_group| %>
    <li class="nav-item dropdown">
      <!--<a class="nav-link" href="/contact_groups/<%= contact_group.id %>">-->
      <!--<a class="nav-link" href="<%= contact_group_path(contact_group) %>">
        <p>
          <%= contact_group.group_name %>
      
        </p>  
      </a>
            <div data-toggle="dropdown">
              <i class="right fas fa-angle-down"></i>
            </div>
            <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
              <a href="<%= edit_contact_group_path(contact_group) %>" class="dropdown-item" data-remote="true">
                <span class="text-muted text-sm">Edit</span>
             </a>
             <a href="<%= new_contact_group_share_invite_path(contact_group) %>" class="dropdown-item" data-remote="true">
                <span class="text-muted text-sm">Share</span>
             </a>
             <a rel="nofollow" data-method="delete" href="<%= contact_group_path(contact_group) %>" class="dropdown-item" data-remote="true">
                <span class="text-muted text-sm">Delete</span>
             </a>

        
      </li> -->
    <!-- Working Button Groups -->
    <div class="btn-group btn-block">    
        <%= link_to contact_group.group_name,  contact_group_path(contact_group), :class => current_class?(contact_group.id, @search_groups_ids) %>
      <div class="btn-group-vertical">        
        <button type="button" class="btn dropdown-toggle sidebar-dropdown" data-toggle="dropdown" aria-expanded="false">
          <span class="caret"></span>
        </button> 
          <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
                <a href="/contact_groups/<%= contact_group.id %>/edit" class="dropdown-item" data-remote="true">
                  <span class="text-muted text-sm">Edit</span>
              </a>
              <a href="/contact_groups/<%= contact_group.id %>/share_invites/new" class="dropdown-item" data-remote="true">
                  <span class="text-muted text-sm">Share</span>
              </a>
              <a rel="nofollow" data-method="delete" href="/contact_groups/<%= contact_group.id %>" class="dropdown-item" data-remote="true">
                  <span class="text-muted text-sm">Delete</span>
              </a>
        </div>
    </div>      
    </li> 
    
  <% end %>
</ul>

app/views/contact_groups/_groups_table.html.erb
<h1>Groups</h1>
<div class="table-responsive">
<table id="group-table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_groups.each do |contact_group| %>
      <tr>
        <td><%= link_to contact_group.group_name,  contact_group_path(contact_group), class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_contact_group_path(contact_group), remote: true %></td>
        <td><%= link_to 'Share', new_contact_group_share_invite_path(contact_group), remote: true %></td>
        <td><%= link_to 'Destroy', contact_group, method: :delete, data: { confirm: "Are you sure? The #{contact_group.group_name} group contains #{pluralize(@contacts.count(), 'record')} which will be lost if you continue!" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Contact Group', new_contact_group_path,  remote: true %>

app/views/contact_groups/_share_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= bootstrap_form_with(model: @contact_group, url: share_create_contact_group_path, remote: true) do |form| %>
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Share</h4>
        <button type="button" class="close" data-dismiss="modal">x</button>
      </div>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <% if flash[:modal_alert] %>
          <p class="alert alert-danger"><%= flash[:modal_alert] %></p>
        <% end %>
      <div class="modal-body">

        <div class="field">
          <%= form.label :share_id, "Email of user you wish to share with:" %>
          <%= form.email_field :share_id, hide_label: true %>
        </div>

      </div>
      <div class="modal-footer">
        <div class="actions" >
          <%= form.submit "Share Group" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contact_groups/create.js.erb
<% if @contact_group.errors%>
$("#shared-modal").html("<%= j (render partial: 'new_form') %>");
$("#shared-modal").modal();
<%else%>
location.reload();
<%end%>

app/views/contact_groups/edit.html.erb
<h1>Editing Contact Group</h1>

<%= render 'form', contact_group: @contact_group %>

<%= link_to 'Show', @contact_group %> |
<%= link_to 'Back', contact_groups_path %>

app/views/contact_groups/edit.js.erb
$("#shared-modal").html("<%= j (render partial: 'edit_form') %>");
$("#shared-modal").modal();

app/views/contact_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Groups</h1>

<table>
  <thead>
    <tr>
      <th>Group name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_groups.each do |contact_group| %>
      <tr>
        <td><%= contact_group.group_name %></td>
        <td><%= link_to 'Show', contact_group %></td>
        <td><%= link_to 'Edit', edit_contact_group_path(contact_group) %></td>
        <td><%= link_to 'Destroy', contact_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Group', new_contact_group_path %>

app/views/contact_groups/new.html.erb
<h1>New Contact Group</h1>

<%= render 'form', contact_group: @contact_group %>

<%= link_to 'Back', contact_groups_path %>

app/views/contact_groups/new.js.erb
$("#shared-modal").html("<%= j (render partial: 'new_form') %>");
$("#shared-modal").modal();

app/views/contact_groups/share_create.js.erb
<% if @contact_group.errors%>
$("#shared-modal").html("<%= j (render partial: 'share_form') %>");
$("#shared-modal").modal();
<%else%>
location.reload();
<%end%>

app/views/contact_groups/share_new.js.erb
<% if current_user.id != @contact_group.owner_id %>
    $("#shared-modal").html("<%= j (render partial: 'not_owner') %>");
<% else %>
    $("#shared-modal").html("<%= j (render partial: 'share_form') %>");
<% end %>

$("#shared-modal").modal();

app/views/contact_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @contact_group.group_name %>
</p>

<%= link_to 'Edit', edit_contact_group_path(@contact_group) %> |
<%= link_to 'Back', contact_groups_path %>

app/views/contact_groups/update.js.erb
<% if @contact_group.errors%>
$("#shared-modal").html("<%= j (render partial: 'edit_form') %>");
$("#shared-modal").modal();
<%else%>
location.reload();
<%end%>