config/routes.rb
Rails.application.routes.draw do
  resources :homes, :only => [:index] do
    collection do 
      get :search_index
    end
  end
  resources :contact_groups do
    resources :share_invites, shallow: true, :only => [:new, :create, :destroy] do
      member do
        get :accept
        get :decline
      end
    end
  end
  resources :contacts
  devise_for :users
  resources :share_invites, :only => [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
end

app/models/share_invite.rb
class ShareInvite < ApplicationRecord
    belongs_to :contact_group
end

app/controllers/share_invites_controller.rb
class ShareInvitesController < ApplicationController
  before_action :set_share_invite, only: [:show, :edit, :update, :destroy]
  before_action :set_contact_group, only: [:new, :create]

  # GET /share_invites
  # GET /share_invites.json
  def index
    @pending_share_invites = ShareInvite.where({receiver_id: current_user.id, status: "pending"})
    @accepted_share_invites = ShareInvite.where({receiver_id: current_user.id, status: "accepted"})
    @sent_share_invites = ShareInvite.where(sharer_id: current_user.id)
    logger.debug "pending- #{@pending_share_invites}"
    logger.debug "accepted- #{@accepted_share_invites}"
  end

  # GET share_invites/:id/accept
  def accept
    logger.debug "params id is set to #{params[:id]}"
    invite = ShareInvite.find(params[:id])
    invite.status = "accepted"
    logger.debug "Invite status is #{invite.status}"
    invite.save
    contact_group = ContactGroup.find(invite.contact_group_id)
    logger.debug "contact_group set to #{contact_group}"
    contact_group.users << User.find(invite.receiver_id)
    redirect_to homes_url, notice: 'Invitation Accepted'
   # @invite = 
  end

  # GET /share_invites/:id/decline
  def decline
    invite = ShareInvite.find(params[:id])
    invite.status = "declined"
    invite.save
    redirect_to homes_url, alert: 'Invitation Declined'
    #link_to "Invites", share_invites_path, remote: true
  end

  # GET /share_invites/1
  # GET /share_invites/1.json
 # def show
 # end

  # GET /share_invites/new
  def new
    logger.debug "new hit"
    @contact_group = ContactGroup.find( params[:contact_group_id])
    logger.debug "@contact_group set to #{@contact_group.group_name}, #{@contact_group}"
    respond_to do |format|
      format.html { logger.debug "Hit as HTML" }
      format.js { logger.debug "Hit as JS" }
    end
  end

  # GET /share_invites/1/edit
 # def edit
 # end

  # POST /share_invites
  # POST /share_invites.json
  def create
    logger.debug "print of params test 1: #{params[:contact_group_id]}"
    logger.debug "print of params test 2: #{params[:share_id]}"
    if User.exists?(email: params[:share_id])
      sharee = User.where(email: params[:share_id]).first!
      #Ensure User being shared to does not already have access to the group
      if sharee.contact_groups.where({ id: params[:contact_group_id] }).blank?
        #Check to see if there is already an invite pending in the users invites
        if ShareInvite.where({receiver_id: sharee.id, contact_group_id: params[:contact_group_id], status: "pending"}).exists?
          respond_to do |format|
            format.html { flash[:modal_alert] = "User already has an invite pending for this group" }
            format.js { flash[:modal_alert] = "User already has an invite pending for this group" }
          end
        else
          #create_invite = ShareInvite.create!( sharer_id: current_user.id, receiver_id: User.where( email: params[:contact_groups][:share_id] ).first.id, contact_group_id: @contact_group.id, status: “pending” )
          create_invite = ShareInvite.create!( sharer_id: current_user.id, receiver_id: sharee.id, contact_group_id: params[:contact_group_id], status: "pending" )

          respond_to do |format|
            format.html { redirect_to homes_url, notice: 'Invite Sent' }
            format.js { redirect_to homes_url, notice: 'Invite Sent' }
          end
        end
      else
        respond_to do |format|
          format.html { flash[:modal_alert] = "Group has already been shared with user" }
          format.js { flash[:modal_alert] = "Group has already been shared with user" }
        end
      end
    else
      respond_to do |format|
        format.html { flash[:modal_alert] = "User does not exist" }
        format.js { flash[:modal_alert] = "User does not exist" }
      end
    end
  end

  # PATCH/PUT /share_invites/1
  # PATCH/PUT /share_invites/1.json
  def update
    respond_to do |format|
      if @share_invite.update(share_invite_params)
        format.html { redirect_to @share_invite, notice: 'Share invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @share_invite }
      else
        format.html { render :edit }
        format.json { render json: @share_invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /share_invites/1
  # DELETE /share_invites/1.json
  def destroy
    contact_group = ContactGroup.find(@share_invite.contact_group_id)
    #logger.debug "Grabbed the contact group #{contact_group} with a list of users of #{contact_group.users}"
    contact_group.users.delete(current_user)
    @share_invite.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: "#{contact_group.group_name} has been removed from your Groups list" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share_invite
      @share_invite = ShareInvite.find(params[:id])
    end

    def set_contact_group
      @contact_group = ContactGroup.find( params[:contact_group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_invite_params
      params.require(:share_invite).permit(:sharer_id, :receiver_id, :contact_group_id, :status)
    end
end

app/helpers/share_invites_helper.rb
module ShareInvitesHelper
end

app/views/share_invites/_form.html.erb
<%= form_with(model: share_invite, local: true) do |form| %>
  <% if share_invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(share_invite.errors.count, "error") %> prohibited this share_invite from being saved:</h2>

      <ul>
        <% share_invite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sharer_id %>
    <%= form.number_field :sharer_id %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.number_field :receiver_id %>
  </div>

  <div class="field">
    <%= form.label :contact_group_id %>
    <%= form.number_field :contact_group_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/share_invites/_index_modal.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Invites</h4>
        <button type="button" class="close" data-dismiss="modal">x</button>
      </div>
      <div class="modal-body">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        
        <table>
          <thead>
            <tr>
              <th>Pending Invites</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% if @pending_share_invites.blank? %>
              <tr>
                <td>No Pending Invites</td>
              </tr>
            <%else%>
              <% @pending_share_invites.each do |share_invite| %>
                <tr>
                  <td><%= User.where( id: share_invite.sharer_id ).first.email%> wishes to share their '<%= ContactGroup.where( id: share_invite.contact_group_id ).first.group_name %>' group with you: </td>
                  <td><%= link_to 'Accept', accept_share_invite_path(share_invite) %></td>
                  <td><%= link_to 'Decline', decline_share_invite_path(share_invite) %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <br>
        <table>
          <thead>
            <tr>
              <th>Accepted Invites</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>
            <% if @accepted_share_invites.blank? %>
              <tr>
                <td>No Accepted Invites</td>
              </tr>
            <%else%>
              <% @accepted_share_invites.each do |share_invite| %>
                <tr>
                  <td><%= User.where( id: share_invite.sharer_id ).first.email%> is sharing their '<%= ContactGroup.where( id: share_invite.contact_group_id ).first.group_name %>' group with you: </td>
                  <td><%= link_to 'Unshare', share_invite, method: :delete, data: { confirm: "Are you sure wish to unshare? If you continue you will lose access the #{ContactGroup.where( id: share_invite.contact_group_id ).first.group_name} group and all associated contacts"} %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <br>
        <table>
          <thead>
            <tr>
              <th>Sent Invites</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>
            <% if @sent_share_invites.blank? %>
              <tr>
                <td>No Invites To Your Groups Sent</td>
              </tr>
            <%else%>
              <% @sent_share_invites.each do |share_invite| %>
                <tr>
                  <td>You sent a request to share your <%= current_user.contact_groups.find(share_invite.contact_group_id).group_name %> with <%= User.where( id: share_invite.receiver_id ).first.email%>: Status "<%= share_invite.status %>" </td>
                  <td style="padding-left:10px;"><%= link_to 'Revoke', share_invite, method: :delete, data: { confirm: "Are you sure wish to Revoke? If you continue you will remove access to the #{ContactGroup.where( id: share_invite.contact_group_id ).first.group_name} group and all associated contacts from #{User.where( id: share_invite.receiver_id ).first.email}"} %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>

      </div>
  </div>
</div>

app/views/share_invites/_invites_table.html.erb
<h1>Share Invites</h1>

<table>
  <thead>
    <tr>
      <th>Invites</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @pending_share_invites.each do |share_invite| %>
      <tr>
        <td><%= User.where( id: share_invite.sharer_id ).first.email%> wishes to share their '<%= ContactGroup.where( id: share_invite.contact_group_id ).first.group_name %>' group with you: </td>
        <!-- <td><%= share_invite.sharer_id %></td>
        <td><%= share_invite.receiver_id %></td>
        <td><%= share_invite.contact_group_id %></td>
        <td><%= share_invite.status %></td> -->
        <td><%= link_to 'Accept', accept_share_invite_path(share_invite) %></td>
        <td><%= link_to 'Decline', decline_share_invite_path(share_invite) %></td>
         <!-- <td><%= link_to 'Destroy', share_invite, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/share_invites/_not_owner.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Share</h4>
      <button type="button" class="close" data-dismiss="modal">x</button>
    </div>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <div class="modal-body">

      <div>
       <p class="alert alert-danger">Must be the owner of the group to share it</p>
      </div>

    </div>
    <div class="modal-footer">
      <div class="actions" >
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/share_invites/_share_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= bootstrap_form_with(model: @share_invite, url: contact_group_share_invites_path, remote: true) do |form| %>
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Share</h4>
        <button type="button" class="close" data-dismiss="modal">x</button>
      </div>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <% if flash[:modal_alert] %>
          <p class="alert alert-danger"><%= flash[:modal_alert] %></p>
        <% end %>
      <div class="modal-body">

        <div class="field">
          <%= form.label :share_id, "Email of user you wish to share with:" %>
          <%= form.email_field :share_id, hide_label: true %>
        </div>

      </div>
      <div class="modal-footer">
        <div class="actions" >
          <%= form.submit "Share Group" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/share_invites/create.js.erb
<% if @contact_group.errors%>
$("#shared-modal").html("<%= j (render partial: 'share_form') %>");
$("#shared-modal").modal();
<%else%>
location.reload();
<%end%>

app/views/share_invites/edit.html.erb
<h1>Editing Share Invite</h1>

<%= render 'form', share_invite: @share_invite %>

<%= link_to 'Show', @share_invite %> |
<%= link_to 'Back', share_invites_path %>

app/views/share_invites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Share Invites</h1>

<table>
  <thead>
    <tr>
      <th>Invites</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @pending_share_invites.each do |share_invite| %>
      <tr>
        <td><%= User.where( id: share_invite.sharer_id ).first.email%> wishes to share their '<%= ContactGroup.where( id: share_invite.contact_group_id ).first.group_name %>' group with you: </td>
        <!-- <td><%= share_invite.sharer_id %></td>
        <td><%= share_invite.receiver_id %></td>
        <td><%= share_invite.contact_group_id %></td>
        <td><%= share_invite.status %></td> -->
        <td><%= link_to 'Accept', accept_share_invite_path(share_invite) %></td>
        <td><%= link_to 'Decline', decline_share_invite_path(share_invite) %></td>
         <!-- <td><%= link_to 'Destroy', share_invite, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Share Invite', new_share_invite_path %>

app/views/share_invites/index.js.erb
$("#shared-modal").html("<%= j (render partial: 'index_modal') %>");
$("#shared-modal").modal();

app/views/share_invites/new.html.erb
<h1>New Share Invite</h1>

<%= render 'form', share_invite: @share_invite %>

<%= link_to 'Back', share_invites_path %>

app/views/share_invites/new.js.erb
<% if current_user.id != @contact_group.owner_id %>
    $("#shared-modal").html("<%= j (render partial: 'not_owner') %>");
<% else %>
    $("#shared-modal").html("<%= j (render partial: 'share_form') %>");
<% end %>

$("#shared-modal").modal();

app/views/share_invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sharer:</strong>
  <%= @share_invite.sharer_id %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @share_invite.receiver_id %>
</p>

<p>
  <strong>Contact group:</strong>
  <%= @share_invite.contact_group_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @share_invite.status %>
</p>

<%= link_to 'Edit', edit_share_invite_path(@share_invite) %> |
<%= link_to 'Back', share_invites_path %>