config/routes.rb
Rails.application.routes.draw do
  resources :homes, :only => [:index] do
    collection do 
      get :search_index
    end
  end
  resources :contact_groups do
    resources :share_invites, shallow: true, :only => [:new, :create, :destroy] do
      member do
        get :accept
        get :decline
      end
    end
  end
  resources :contacts
  devise_for :users
  resources :share_invites, :only => [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_contact_groups
  before_action :create_group_if_none
  before_action :set_contact_group_session
  before_action :set_share_invites
  before_action :set_welcome_message_shown

  # GET /homes
  # GET /homes.json
  def index
    
#    if session[:welcome_message_shown].present? && session[:welcome_message_shown] == "false"
#      render :js => 'welcome'
#    end 
    @contacts = @current_contact_group.contacts.order_by_name;
    # @contacts = Contact.where({ user_id: "current_user.id", id: "session[:contact_group_id]" }).order_by_name
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  # GET /homes/search_index
  def search_index
    logger.debug "search term is #{params[:search_term]}"
    search_term_lower = params[:search_term].downcase
    logger.debug "lowercased term is #{search_term_lower}"
    @contacts = current_user.contacts.where('first_name ILIKE ? OR last_name ILIKE ? OR phone_number ILIKE ? OR contact_email ILIKE ?', "%#{search_term_lower}%", "%#{search_term_lower}%", "%#{search_term_lower}%", "%#{search_term_lower}%")
    @search_groups_ids = @contacts.distinct.pluck(:contact_group_id)
    if @search_groups_ids.blank?
    else
      logger.debug "Below is an inspect of the array search contacts"
      logger.debug @search_groups_ids.inspect
    end
    render "index" 
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_share_invites
      @pending_share_invites = ShareInvite.where({receiver_id: current_user.id, status: "pending"})
      @accepted_share_invites = ShareInvite.where({receiver_id: current_user.id, status: "accepted"})
    end

    def set_contact_groups
      @contact_groups = current_user.contact_groups.order(:group_name)
    end

    def create_group_if_none
      if @contact_groups.present?
        logger.debug "contact_group exists"
      else
        default_contact_group = ContactGroup.create(group_name: "Default", default: "true", owner_id: current_user.id )
        default_contact_group.users << current_user
        @contact_groups = [default_contact_group]
        logger.debug "contact_groups #{default_contact_group}"
        logger.debug "Default contact_group created"
      end
    end

    def set_contact_group_session
      if session[:contact_group_id].present?
        if @current_contact_group = current_user.contact_groups.where( id: session[:contact_group_id]).first
          logger.debug "contact_group_id is #{session[:contact_group_id]}"
        else
          @current_contact_group = current_user.contact_groups.where( default: true ).first!
          logger.debug "contact_group_id is #{session[:contact_group_id]}"
        end
      else
         @current_contact_group = current_user.contact_groups.where( default: true ).first!
         session[:contact_group_id] = @current_contact_group.id
        logger.debug "Default contact_group session created and set to #{session[:contact_group_id]}"
      end
    end

    def set_welcome_message_shown
      if session[:welcome_message_shown].nil?
        session[:welcome_message_shown] = false
      else
        session[:welcome_message_shown] = true
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_navbar.html.erb
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-light navbar-white">
    <div class="container">
      <ul class="navbar-nav">  
        <!--<li class="nav-item d-block d-md-none">-->
        <li class="nav-item d-block d-md-none">
          <a class="nav-link" data-widget="pushmenu" href="#">
            <i class="fas fa-bars"></i>
          </a>
        </li>
      </ul>
      <a class="navbar-brand">
        <span class="brand-text font-weight-light">Mint Book</span>
      </a>

      <!-- Left navbar links
      <ul class="navbar-nav">
        <li class="nav-item">
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="#" class="nav-link">Contact</a>
        </li>
      </ul> -->

      <!-- SEARCH FORM -->
      <form action="/homes/search_index" method="get" class="form-inline ml-3">
        <div class="input-group input-group-sm">
          <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search" id="search_term" name="search_term">
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Invites Menu -->
        <li class="nav-username">
          <%= current_user.email %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to share_invites_path, remote: true, class: "nav-link" do%>
            <i class="fas fa-envelope"></i>
            <% if @pending_share_invites.blank? %>
            <% else %>
              <span class="badge badge-danger navbar-badge"><%= @pending_share_invites.count %></span>
            <% end %>
          <%end%>
          
          
        <!-- Sign out Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown">
            <i class="fas fa-sign-out-alt"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>

      </ul>
    </div>
  </nav>
  <!-- /.navbar -->

app/views/homes/_sidebar.html.erb
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <!--<a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8"> -->
      <h2 style="color:rgb(194, 199, 208); padding-top: 10px; padding-left: 15px;">Groups</h2>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) 
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
    </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
           <li class="nav-item has-treeview menu-open">            
          <%= render 'contact_groups/groups_nav' %>
          </li> 
          <li class="nav-item">
            <a data-remote="true" href="<%= new_contact_group_path %>" class="nav-link">
              <i class="far fa-plus-square"></i>
              <p>
                 New Group
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/homes/_welcome_message.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Welcome!</h4>
        <button type="button" class="close" data-dismiss="modal">x</button>
      </div>
      <div class="modal-body">
        <p>Welcome to Mint Book!</p>
        <P>The Mint Address Book, or "Mint Book", is a little project I put together when I first started learning rails.
          As I've grown in my rails abilities I've peroidically come back to this project, and so the Mint Book has grown too.
          For those curious to know what it's all about I've outlined so key features, as well as the technologies used in this project.
        </p>

        <p>Key Features</p>
        <ul style="list-style-type:disc;">
          <li>Ability to create and organize contacts into contact groups</li>
          <li>Cross account invites and sharing of contact groups between users</li>
          <li>Search functionality accross all groups to find the contacts you want</li>
          <li>Page layout dynamically changes to fit smaller screen sizes (phone and tablet)</li>
          <li>Dynamic class association</li>
        </ul>
        

        <p>Technologies Used</p>
        <ul style="list-style-type:disc;">
          <li>Rails 6</li>
          <li>Postgresql</li>
          <li>Heroku</li>
          <li>Devise</li>
          <li>Bootstrap 4</li>
          <li>Adminlte 3</li>
        </ul>
        
        <p>Without further ado, I bring you Mint Book!  </p>
        <p class="text-right" style="padding-right:5px;">-Ron Sloop Jr.</p>

      </div>
      <div class="modal-footer">
        <div class="actions" >
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
  </div>
</div>

app/views/homes/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-10">
      <%= render 'contacts/table_adminlte' %>
    </div>
  </div>
</div>
<%logger.debug "the value of session variable welcome_message_shown is #{session[:welcome_message_shown]}"%>
<% if session[:welcome_message_shown] == false %>
  <script>$("#shared-modal").html("<%= j (render partial: 'welcome_message') %>");  $("#shared-modal").modal();</script>
<%end%>